# Generated by Django 6.0.3 on 2026-04-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker_api', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Investments', 'Investments'), ('Gift', 'Gift'), ('Miscellaneous Income', 'Miscellaneous Income'), ('Rent/Mortgage', 'Rent/Mortgage'), ('Groceries', 'Groceries'), ('Dining Out', 'Dining Out'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Insurance', 'Insurance'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Miscellaneous Expense', 'Miscellaneous Expense')], default='Miscellaneous Expense', max_length=50),
        ),
    ]
